# conda env create --name COmapper --file environment.yaml
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9.19
  - pandas=1.1.3
  - typing-extensions=4.12.2
  - minimap2=2.28
  - samtools=1.20
  - sambamba=1.0.1
